### PR TITLE
Enhance kafka message provider

### LINKED ISSUE #3022: services.KafkaConnectorTests.Kafka heisenbug
This issue is to collect the intermittent issues. We found three different types so far:
- [ ] `This server is not the leader for that topic-partition.`
- [ ] `services.KafkaConnectorTests > Kafka connector should send and receive a kafka message even after shutdown one of instances FAILED
    org.scalatest.exceptions.TestFailedException: 0 was not equal to 1`
- [ ] hanging while trying to retrieve a message https://github.com/apache/incubator-openwhisk/issues/3022#issuecomment-348948838

Observed one failure in jenkins:

```bash
services.KafkaConnectorTests.Kafka connector should send and receive a kafka message even after shutdown one of instances

Error Message

org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.

Stacktrace

org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.

Standard Output

[2017-11-28T15:07:19.923Z] [INFO] Slf4jLogger started
Received 1. Took 407 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 3 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:20 EST 2017)

Received 2. Took 11 msec: List(Tue Nov 28 15:07:20 EST 2017, Tue Nov 28 15:07:31 EST 2017)

Received 3. Took 9 msec: List(Tue Nov 28 15:07:20 EST 2017, Tue Nov 28 15:07:31 EST 2017, Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 4 msec: List(Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 7 msec: List(Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 10 msec: List(Tue Nov 28 15:07:42 EST 2017)

Received 1. Took 22 msec: List(Tue Nov 28 15:07:52 EST 2017)


```

### PR DESCRIPTION
**Pull request by devbv**
- Make sessionTimeout configurable
- Handle exception from Kafka broker down
- Reuse docker command functions

Resolve #3022

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Can you provide tests for the failure scenarios you implemented here?

In general I have the feeling that we're moving into a direction here, which should not really be our business. That is: Write a resilient client to talk to Kafka/a Kafka cluster. Personally, I don't grasp all the error-cases implemented here and neither do I know if the code is complete in it's error handling.

A possibility is to move to a well tested client (like https://github.com/cakesolutions/scala-kafka-client or https://doc.akka.io/docs/akka-stream-kafka/current/home.html). Quite frankly that will be a larger operation than this so I'm a bit unsure on how to proceed. What do you think?

**Comment by devbv** [comment]
@markusthoemmes @jeremiaswerner 
I can't write test case for almost scenarios because they are intermittent issues from Kafka fail-over and rebalancing and it is so hard to recreate it manually. 
My purpose was trying to success all user request by handling exceptions and adding fallbacks, even there are node fails in kafka cluster.
If it is ok to allow all errors and response user request as a internal error when kafka issues occur, I definitely agree with that we don't need to handle exceptions and it's quite large operation. So if you thought in that way, I would get rid of all error handling and retry logics!
And in that case, our kafka shooting up test should be changed to something like "Allow at most 3 errors for 10 request".
So give me opinons, I'll gladly follow yours.

**Comment by markusthoemmes** [comment]
Okay, that makes sense.

The major difference from the better-known clients is, that their error behavior is more principled (i.e. controllable via a `SupervisionStrategy`).

In any case: If we make sure that:

1. Errors we know of  are handled
2. Errors we don't know of just result in a restart of the consumer/producer

I guess we are fine.

I'll review more thoroughly tomorrow. Testing new clients/completely moving away from our own ones is a much larger task that should be seen orthogonal.

**Comment by devbv** [comment]
@markusthoemmes I think some types of RetriableException could duplicate the message if we tried to send a message again. I'm pretty sure that InvalidMetadata guarantees that we really fail to send a message, but cannot sure it when TimeoutException is raised.

And you can see here, producer retries will cause duplicates for NotEnoughReplicasAfterAppendException
https://kafka.apache.org/0100/javadoc/org/apache/kafka/common/errors/NotEnoughReplicasAfterAppendException.html

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 1]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
    * @param duration the maximum duration for the long poll
    */
-  override def peek(duration: Duration = 500.milliseconds) = {
-    val records = consumer.poll(duration.toMillis)
-    records map { r =>
-      (r.topic, r.partition, r.offset, r.value)
+  override def peek(duration: Duration = 500.milliseconds,
+                    retry: Int = 3): Iterable[(String, Int, Long, Array[Byte])] = {
+    // Since kafka client can be infinitely blocked in poll(timeout), we should interrupt it by wakeup() method
+    val wakeUpTask = actorSystem.scheduler.scheduleOnce(sessionTimeout) {
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: Why `sessionTimeout`? Shouldn't we do `duration + someGraceTime`?

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 2]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
+import org.apache.kafka.common.errors.{InvalidMetadataException, WakeupException}
+import akka.actor.ActorSystem
+import org.apache.kafka.common.KafkaException
 import whisk.common.Logging
 import whisk.core.connector.MessageConsumer
 
 class KafkaConsumerConnector(kafkahost: String,
                              groupid: String,
                              topic: String,
+                             actorSystem: ActorSystem,
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: You might want to pass this in as an implicit parameter.

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 3]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
 
   /**
    * Commits offsets from last poll.
    */
-  def commit() = consumer.commitSync()
+  def commit(retry: Int = 3): Unit =
+    try {
+      consumer.commitSync()
+    } catch {
+      case error: InvalidMetadataException =>
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: Can we use `RetrieableException` here instead?

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 4]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
+    // Since kafka client can be infinitely blocked in poll(timeout), we should interrupt it by wakeup() method
+    val wakeUpTask = actorSystem.scheduler.scheduleOnce(sessionTimeout) {
+      consumer.wakeup()
     }
+
+    try {
+      val records = consumer.poll(duration.toMillis)
+      records map { r =>
+        (r.topic, r.partition, r.offset, r.value)
+      }
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: FWIW: This can be 

```scala
consumer.poll(duration.toMillis).map(r => (r.topic, r.partition, r.offset, r.value))
```

File: ansible/roles/controller/tasks/deploy.yml [hunk 5]
```diff
@@ -62,6 +62,7 @@
       "CONFIG_whisk_kafka_topics_health_retentionBytes": "{{ kafka_topics_health_retentionBytes | default() }}"
       "CONFIG_whisk_kafka_topics_health_retentionMs": "{{ kafka_topics_health_retentionMS | default() }}"
       "CONFIG_whisk_kafka_topics_health_segmentBytes": "{{ kafka_topics_health_segmentBytes | default() }}"
+      "KAFKA_SESSIONTIMEOUT": "{{ kafka.sessionTimeout }}"
```
Comment (markusthoemmes) [inline ansible/roles/controller/tasks/deploy.yml]: Please move that line below KAFKA_HOSTS.

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 6]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
+       * 1. Error we know of can be handled by retry
+       *  - WakeupException: Exception we raise intentionally to prevent hanging in consumer.poll(timeout)
+       *  - InvalidMetadataException: An exception that may indicate the client's metadata is out of date,
+       *                              includes NetworkException, KafkaStorageException, LeaderNotAvailableException,
+       *                              NotLeaderForPartitionException, UnknownTopicOrPartitionException.
+       *
+       * 2. Errors we don't know of just result in a restart of the consumer/producer
+       *
+       */
+      case e: KafkaException =>
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: As discussed: Can we just go with `RetriableException`  in the KafkaConsumer?

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 7]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
+        e match {
+          case _: WakeupException =>
+            if (retry > 0) {
+              logging.error(this, s"Poll timeout occurred, remain $retry retries to peek")
+              peek(duration, retry - 1)
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: Do we want/need to delay the retry for a bit?

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala [hunk 8]
```diff
@@ -66,12 +70,33 @@ class KafkaProducerConnector(kafkahosts: String,
...
+       *
+       * 1. Error we know of can be handled by retry
+       *  - InvalidMetadataException: An exception that may indicate the client's metadata is out of date,
+       *                              includes NetworkException, KafkaStorageException, LeaderNotAvailableException,
+       *                              NotLeaderForPartitionException, UnknownTopicOrPartitionException.
+       *
+       * 2. Errors we don't know of just result in a restart of the consumer/producer
+       *
+       */
+      case e: KafkaException =>
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala]: Can we use `RetriableException` and exclude the ones we deem harmful?

```scala 
case _: NotEnoughReplicasAfterAppendException =>
  recreateProducer()
  produced.future
case _: RetriableException =>
  ...
case _ =>
  recreateProducer()
  produced.future
```

File: common/scala/src/main/scala/whisk/core/connector/MessagingProvider.scala [hunk 9]
```diff
@@ -31,6 +33,7 @@ trait MessagingProvider extends Spi {
   def getConsumer(config: WhiskConfig,
                   groupId: String,
                   topic: String,
+                  actorSystem: ActorSystem,
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/core/connector/MessagingProvider.scala]: Want to move this to the implicit section?

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 10]
```diff
@@ -21,46 +21,106 @@ import java.util.Properties
...
+            } else {
+              recreateConsumer()
+              throw e
+            }
+          case _: InvalidMetadataException =>
+            if (retry > 0) {
+              logging.error(this, s"${e.getMessage}: remain $retry retries to peek")
+              wakeUpTask.cancel()
```
[the remark this answers is not in the document]
Comment (devbv) [reply common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: Not really, each retry creates own wakeUpTask so we should cancel it every retry.

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala (hunk 8 above)
Comment (devbv) [reply common/scala/src/main/scala/whisk/connector/kafka/KafkaProducerConnector.scala]: Great idea

**Comment by devbv** [comment]
After rebase, a failed test would be resolved.
(https://github.com/apache/incubator-openwhisk/commit/50c0142e9543b38ba2807b1c734c5af6c3116d72)

**Comment by devbv** [comment]
@markusthoemmes Everything is ok

**Comment by markusthoemmes** [comment]
@rabbah can you please sanity check this?

File: ansible/group_vars/all [hunk 11]
```diff
@@ -135,6 +135,7 @@ kafka:
     port: 8093
   heap: "{{ kafka_heap | default('1g') }}"
   replicationFactor: "{{ kafka_replicationFactor | default((groups['kafkas']|length)|int) }}"
+  sessionTimeout: 30000
```
Comment (rabbah) [inline ansible/group_vars/all]: do these values make sense as pure config props as well?

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 12]
```diff
@@ -21,46 +21,91 @@ import java.util.Properties
...
    * Commits offsets from last poll.
    */
-  def commit() = consumer.commitSync()
+  def commit(retry: Int = 3): Unit =
+    try {
+      consumer.commitSync()
+    } catch {
+      case e: RetriableException =>
+        if (retry > 0) {
+          logging.error(this, s"$e: retrying $retry more times")
```
Comment (rabbah) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: (nit warning ahead): how about `retries left: $retry` to avoid this reading `retrying 1 more times` here and elsewhere above and below.

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 13]
```diff
@@ -89,9 +134,18 @@ class KafkaConsumerConnector(kafkahost: String,
...
+  private def recreateConsumer(): Unit = {
+    val oldConsumer = consumer
+    Future {
+      oldConsumer.close()
+      logging.info(this, s"old consumer closed")
+    }
+    consumer = getConsumer(getProps, Some(List(topic)))
+  }
+
+  @volatile private var consumer = getConsumer(getProps, Some(List(topic)))
```
Comment (rabbah) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: i'm not sure that this needs to be volatile (and hence incur the performance implications); in the architecture (controller's pings and active acks, or invoker activation feed) there is one actor that is connected to the message consumer and it serializes all the reads from the message bus.

File: common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala [hunk 14]
```diff
@@ -60,8 +60,9 @@ class RemoteCacheInvalidation(config: WhiskConfig, component: String, instance:
   private val instanceId = s"$component${instance.toInt}"
 
   private val msgProvider = SpiLoader.get[MessagingProvider]
-  private val cacheInvalidationConsumer = msgProvider.getConsumer(config, s"$topic$instanceId", topic, maxPeek = 128)
-  private val cacheInvalidationProducer = msgProvider.getProducer(config, ec)
+  private val cacheInvalidationConsumer =
```
Comment (rabbah) [inline common/scala/src/main/scala/whisk/core/database/RemoteCacheInvalidation.scala]: no change on this line, can the RHS move back to same line?

**Comment by rabbah** [comment]
LGTM in general; although I don't understand why the poll interrupt is needed and want to investigate that on my own.

File: common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala [hunk 15]
```diff
@@ -21,46 +21,91 @@ import java.util.Properties
...
    * @param duration the maximum duration for the long poll
    */
-  override def peek(duration: Duration = 500.milliseconds) = {
-    val records = consumer.poll(duration.toMillis)
-    records map { r =>
-      (r.topic, r.partition, r.offset, r.value)
-    }
+  override def peek(duration: Duration = 500.milliseconds,
+                    retry: Int = 3): Iterable[(String, Int, Long, Array[Byte])] = {
+    // Since kafka client can be infinitely blocked in poll(timeout), we should interrupt it using the wakeup() method
```
Comment (markusthoemmes) [inline common/scala/src/main/scala/whisk/connector/kafka/KafkaConsumerConnector.scala]: Can you elaborate on why the poll could be blocked infinitely? In theory, the timeout should limit the time it can be blocked? Is this for edge cases (i.e. lost connection)?

**Comment by markusthoemmes** [comment]
I clarified the remaining bits with Kafka experts. Consider this scheduled for merge after #3258 to minimize conflicts.

@devbv I'll take care of the rebase if you want.

**Comment by devbv** [comment]
@markusthoemmes 
Sorry for late reply. Recently I'm focusing on the other project in company, so I don't have much time to take care of it. Please rebase and merge. :)

**Comment by markusthoemmes** [comment]
PG3 1895 🔵
