### PR TITLE
Correct unable to set apihost issue.

### LINKED ISSUE #2411: Unable to set the api host
## Environment details:

* Ubuntu 16.04 
* Docker version 1.12.0, build 8eab29e

## Steps to reproduce the issue:

1.   try setting apihost like below
2.   ./wsk property set --apihost 10.xxx.11.xx:5009
3.   since the api host is having port no it will throw error 

## Provide the expected results and outputs:

```
ok: whisk API host set to 10.xxx.11.xx:5009
```

## Provide the actual results and outputs:

```
runtime error: invalid memory address or nil pointer dereference
Application exited unexpectedly
```

## Additional information you deem important:
* i have distributed OW setup with    
* i am using HAProxy as LB. 
* i wanted to add LB ip and port as api host

### PR DESCRIPTION
**Pull request by lzbj**
line 864 url.Parse caused failure.
Fixes #2411.

### CODE REVIEW

**Comment by dubeejw** [comment]
@lzbj, commented on the issue about port setting as well.

File: tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala [hunk 1]
```diff
@@ -151,7 +151,7 @@ class WskBasicUsageTests
         val tmpwskprops = File.createTempFile("wskprops", ".tmp")
         try {
             val env = Map("WSK_CONFIG_FILE" -> tmpwskprops.getAbsolutePath())
-            val apihost = s"http://${WhiskProperties.getBaseControllerAddress()}"
+            val apihost = s"${WhiskProperties.getBaseControllerAddress()}"
```
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: @lzbj, need a test for setting the API host with and without a protocol.

Comment (dubeejw) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: @lzbj, also looks like the test failed because the server is expecting an http request instead of an https request.

Comment (dubeejw) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: I believe the original error comes from the `url.Parse(urlBase)` function.

Comment (lzbj) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: Yes, correct, I'll update according to your comments.

File: tools/cli/go-whisk-cli/commands/util.go [hunk 2]
```diff
@@ -856,6 +856,10 @@ func getURLBase(host string, path string) (*url.URL, error)  {
         return nil, whiskErr
     }
 
+    if !strings.HasPrefix(host, "http") {
+        host = "http://" + host
```
Comment (dubeejw) [inline tools/cli/go-whisk-cli/commands/util.go]: What if the OpenWhisk deployment only supports https?

Comment (dubeejw) [inline tools/cli/go-whisk-cli/commands/util.go]: I believe the error is thrown blow on line 864 `url.Parse`.

Comment (lzbj) [inline tools/cli/go-whisk-cli/commands/util.go]: correct, updated the code. If we can't avoid deployment using https, we can just add one test. do you have any suggestion we can add more tests?

**Comment by rabbah** [comment]
The cli must support both - there's a test for http as well as https which is the nginx path.

**Comment by lzbj** [comment]
Ok, thank you. Then now the test in WskBasicUsageTests is sufficient for the change, right?

**Comment by rabbah** [comment]
@dubeejw @mdeuser thoughts?

File: tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala [hunk 3]
```diff
@@ -148,7 +148,7 @@ class WskBasicUsageTests
         }
     }
 
-    it should "show api build using http apihost" in {
+    it should "show api build using http apihost with protocol specified" in {
```
Comment (mdeuser) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: @lzbj - is another successful test needed that provides the api host without the protocol being provided?

Comment (mdeuser) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: this is the area of code i was considering
```
+    if !strings.HasPrefix(host, "http") {
+        host = "https://" + host
+    }
```
so i was thinking an apihost setting with and without a http prefix should work.  will a protocol-less apihost fail?

Comment (lzbj) [inline tests/src/test/scala/whisk/core/cli/test/WskBasicUsageTests.scala]: yes, this line "I believe the error is thrown blow on line 864 url.Parse." will fail as @dubeejw comments.

File: tools/cli/go-whisk-cli/commands/util.go [hunk 4]
```diff
@@ -841,6 +841,10 @@ func getURLBase(host string, path string) (*url.URL, error)  {
         return nil, whiskErr
     }
 
+    if !strings.HasPrefix(host, "http") {
```
Comment (dubeejw) [inline tools/cli/go-whisk-cli/commands/util.go]: Hmm, what if the string begins with `https://`, won't `https://` be prepended again?

File: tools/cli/go-whisk-cli/commands/util.go [hunk 5]
```diff
@@ -841,6 +841,10 @@ func getURLBase(host string, path string) (*url.URL, error)  {
...
+        host = "https://" + host
```
Comment (dubeejw) [inline tools/cli/go-whisk-cli/commands/util.go]: Need a test for this.

**Comment by rabbah** [comment]
I don't know if this pr is still relevant but it doesn't fix this issue:

```
> wsk property set --apihost http://192.168.99.100
> wsk action create t echo.js --web true
ok: created action t
> wsk action get t --url
ok: got action t
https://http://192.168.99.100/api/v1/web/guest/default/t
```

**Comment by rabbah** [comment]
@mdeuser @dubeejw @lzbj i pushed a commit which adds tests.

**Comment by lzbj** [comment]
@rabbah , thanks.

File: tests/src/test/scala/whisk/core/cli/test/WskConfigTests.scala [hunk 6]
```diff
@@ -259,6 +259,27 @@ class WskConfigTests extends TestHelpers with WskTestHelpers {
...
+  it should "set api host with or without http prefix" in {
+    val tmpwskprops = File.createTempFile("wskprops", ".tmp")
+    try {
+      val env = Map("WSK_CONFIG_FILE" -> tmpwskprops.getAbsolutePath())
+      Seq("", "http://", "https://").foreach { prefix =>
+        Seq("10", "10:123", "aaa", "aaa:123").foreach { host =>
+          val apihost = s"$prefix$host"
+          withClue(apihost) {
+            val rr = wsk.cli(Seq("property", "set", "--apihost", apihost), env = env)
+            rr.stdout should not include regex("Application exited unexpectedly")
```
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/cli/test/WskConfigTests.scala]: Errors are printed to `stderr`, so shouldn't need this check.

**Comment by rabbah** [comment]
pg1/2055 🚀

**Comment by rabbah** [comment]
pg is blue.
