### PR TITLE
Better error controller message for authorization failure

### LINKED ISSUE #1684: better error message for authorization failure
```wsk action create --sequence cats /whisk.system/utils/echo,/someNamespace/list-documents -p dbname cats
error: Unable to create action: The supplied authentication is not authorized to access this resource. (code 6035175) 
```

Whenever we report an error message about "this resource",  we should instead explicitly name the resource that caused the problem in the error message.

Additionally, if "this resource" does not exist, we should produce an error message saying so explicitly.

### PR DESCRIPTION
**Pull request by mdeuser**
Fixes #1684

### CODE REVIEW

**Comment by mdeuser** [comment]
pg2/2187

**Comment by dubeejw** [comment]
@mdeuser, you need to run `gradle scalafmtAll` from OpenWhisk root directory then commit the changes in order to get Travis to pass.

File: core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala [hunk 1]
```diff
@@ -71,7 +74,21 @@ trait BasicAuthorizedRouteProvider extends Directives {
...
+                handleEntitlementFailure(
+                  RejectRequest(
+                    Forbidden,
+                    Some(ErrorResponse(Messages.notAuthorizedtoAccessResource(resource.fqname), transid))))
+              case NotFound =>
+                handleEntitlementFailure(
+                  RejectRequest(NotFound, Some(ErrorResponse(Messages.resourceDoesntExist(resource.fqname), transid))))
+              case _ => handleEntitlementFailure(t)
+            }
+        }
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala]: Does this disambiguate access to your own namespace vs. access to any other namespace? We shall not return `not found` if we don't even have access to that namespace because then we'd leak information from other peoples namespaces.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala [hunk 2]
```diff
@@ -56,6 +58,7 @@ protected[core] case class Resource(namespace: EntityPath,
                                     env: Option[Parameters] = None) {
   def parent = collection.path + EntityPath.PATHSEP + namespace
   def id = parent + (entity map { EntityPath.PATHSEP + _ } getOrElse (""))
+  def fqname = namespace + (entity map { EntityPath.PATHSEP + _ } getOrElse (""))
```
Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: namespace is not of type String - should use namespace.asString instead.

File: tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala [hunk 3]
```diff
@@ -591,7 +591,7 @@ class PackageActionsApiTests extends ControllerTestCommon with WhiskActionsApi {
     val auser = WhiskAuthHelpers.newIdentity()
     Get(s"/${provider.namespace}/${collection.path}/${provider.name}/${entity.name}") ~> Route.seal(routes(auser)) ~> check {
       status should be(Forbidden)
-      responseAs[ErrorResponse].error shouldBe Messages.notAuthorizedtoOperateOnResource
+      responseAs[ErrorResponse].error shouldBe Messages.notAuthorizedtoAccessResource(s"${namespace}/${provider.name}")
```
Comment (rabbah) [inline tests/src/test/scala/whisk/core/controller/test/PackageActionsApiTests.scala]: don't need `{}` around a `namespace`: `$namespace`.

File: tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala [hunk 4]
```diff
@@ -534,25 +536,27 @@ class EntitlementProviderTests extends ControllerTestCommon with ScalaFutures {
...
     implicit val ep = entitlementProvider
 
+    val provider = WhiskPackage(someUser.namespace.toPath, MakeName.next(), None, publish = true)
+    val binding = WhiskPackage(guestUser.namespace.toPath, MakeName.next(), provider.bind)
+    val action = WhiskAction(binding.fullPath, MakeName.next(), jsDefault(""))
+    put(entityStore, provider)
+    put(entityStore, binding)
+    put(entityStore, action)
+
+    val resourceName = s"${binding.namespace}/${binding.name}"
```
Comment (rabbah) [inline tests/src/test/scala/whisk/core/controller/test/EntitlementProviderTests.scala]: I suggest using `binding.fullyQualifiedName(false).asString` instead here and elsewhere a name is constructed explicitly.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala [hunk 5]
```diff
@@ -193,7 +199,14 @@ protected[core] abstract class EntitlementProvider(config: WhiskConfig, loadBala
...
       if (isAuthorized) Future.successful({})
-      else Future.failed(RejectRequest(Forbidden))
+      else
+        Future.failed(
+          RejectRequest(
+            Forbidden,
+            Some(
+              ErrorResponse(
+                Messages.notAuthorizedtoAccessResource(resources.map(r => r.fqname).mkString(", ")),
+                transid))))
```
Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: I don't think this is particularly helpful - the priv check is over a set of resources, and `isAuthorized` is a predicate that must hold over all of them. At this point, you can't disambiguate which of the resources was the one that failed the check. So the message is a blanket failure accessing all resources instead of the possibly just one that failed.

Comment (mdeuser) [reply core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: yep.  i wanted to only include the specific resource(s) in the set that were not accessible, but, as you mentioned, the lower level method performing the access check returned a single boolean as the all-or-nothing accessibility value.  if this is not a common use case, perhaps this message can be left as it currently is - without naming any particular resource; otherwise, additional changes will be needed to surface inaccessible resource(s).

File: core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala (hunk 1 above)
Comment (mdeuser) [reply core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala]: @markusthoemmes - not sure i completely understand the question.  if a user does not have authority to access the targeted `namespace + entity` or `namespace + package + entity`, a forbidden response will be returned - even if the namespace does not exist.  from what i've seen, the target resource name displayed will be dependent on the resource being checked.  that value might be `ns/pkg` or `ns` or `ns/entity`.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala (hunk 5 above)
Comment (rabbah) [reply core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: You could refactor the individual resource checks and resolve all the promises later where you can provide the extra information. I think that’s the sprit if the issue as it would apply to sequences.

Comment (mdeuser) [reply core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: @rabbah - is there a way to use the CLI to cause an auth check on a set of resources?  i think i have a refactored approach, but i'm not sure that the current automated tests exercise this code path.
/cc @dubeejw

Comment (rabbah) [reply core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: I'd create a unit test where it's easier to mock this instead of trying to do it through the CLI.

**Comment by mdeuser** [comment]
@rabbah @dubeejw - code has been updated per comments.  let me know if there's any other needed changes

pg4/990

File: core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala (hunk 1 above)
Comment (rabbah) [reply core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala]: @markusthoemmes the entitlement should yield different rejection codes (forbidden or not found) depending on the subject and their rights. There should be tests for this.

**Comment by rabbah** [comment]
I think the way sequence and rule entitlement works, we need to do more here for the case where an action does not exit. This could be a secondary PR. You can verify this by creating a test which creates a sequence with two actions `a` and `b` where only one of these exists.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala [hunk 6]
```diff
@@ -175,13 +181,34 @@ protected[core] abstract class EntitlementProvider(config: WhiskConfig, loadBala
...
+                }
+              }
+              .map { _.forall(identity) }
+          })
       } else Future.successful(true)
     } else if (right != REJECT) {
+      resources.map(r => inaccessibleResources += r)
       logging.info(
         this,
         s"supplied authkey for user '$subject' does not have privilege '$right' for '${resources.mkString(",")}'")
```
Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: i'd separate with `, ` (a space after comma) for better readability.

File: core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala (hunk 1 above)
Comment (mdeuser) [reply core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala]: _thinking out loud_  to limit the amount of information giving to an attacker, handing out a single response for either forbidden or not found seems like a good way to avoid resource name discovery.

**Comment by rabbah** [comment]
In general yes but here the resources are explicitly named in the request. I’m not sure I see the point of hiding details beyond not found vs forbidden.

**Comment by mdeuser** [comment]
@dubeejw - this one is ready to squash/merge.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala [hunk 7]
```diff
@@ -195,21 +200,45 @@ protected[core] abstract class EntitlementProvider(config: WhiskConfig, loadBala
...
-        logging.info(this, s"checking user '$subject' has privilege '$right' for '${resources.mkString(",")}'")
+        logging.info(this, s"checking user '$subject' has privilege '$right' for '${resources.mkString(", ")}'")
         checkSystemOverload(right)
           .flatMap(_ => checkUserThrottle(user, right, resources))
           .flatMap(_ => checkConcurrentUserThrottle(user, right, resources))
           .flatMap(_ => checkPrivilege(user, right, resources))
+          .flatMap(resourcePrivSet => {
+            Future
+              .sequence {
+                resourcePrivSet.map { resourcePriv =>
```
Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: you could filter the resource priv set on `._2` and check if the resultant list is empty, this would save the map+forall later and the construction of `inaccessibleResources` explicitly.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala [hunk 8]
```diff
@@ -232,23 +270,24 @@ protected[core] abstract class EntitlementProvider(config: WhiskConfig, loadBala
...
-              entitled(user.subject, right, resource)
-          }
+    Future.sequence {
+      resources.map { resource =>
+        resource.collection.implicitRights(user, defaultNamespaces, right, resource) flatMap {
+          case true => Future.successful(resource -> true)
+          case false =>
+            logging.info(this, "checking explicit grants")
+            entitled(user.subject, right, resource) flatMap {
+              case true  => Future.successful(resource -> true)
```
Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: This should just be `x => Future.successful(resource -> x)`.

File: core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala (hunk 1 above)
Comment (rabbah) [reply core/controller/src/main/scala/whisk/core/controller/AuthorizedRouteDispatcher.scala]: In general yes but here the resources are explicitly named in the request. I’m not sure I see the point of hiding details beyond not found vs forbidden.

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala (hunk 7 above)
Comment (mdeuser) [reply core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: i wasn't sure how to escape the Future flatmap cycle to produce a non-Future map.  i made an update close to what you've suggested

**Comment by rabbah** [comment]
@dubeejw when you merge a pr that is not squashed can you sanitze the commit message so it doesn't come through like this one:

```
* Add resource name to Forbidden error message

* Comment updates and test case updates

* Fix scalafmt issue

* Reformat using scalafmt plugin

* Fix two more failing test cases

* Comment updates

* Compiles but tests are broken

* Add Set[Resources] test

* Comment updates

* Comment updates
```

File: core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala (hunk 7 above)
Comment (rabbah) [reply core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala]: OK I will attempt this and can submit a patch.

**Comment by dubeejw** [comment]
@rabbah, sure thing.
