### PR TITLE
Ping test should check for absence of ping response

### LINKED ISSUE #4013: Ping test should be more leninet in expected message
`Whisk actions should not be able to use 'ping' in an action` test currently checks for specific error message and thus fails for our setup where message is different. Ours `ping: permission denied (are you root?)` vs expected `ping: icmp open socket: Operation not permitted`

Test failure message

```
org.scalatest.exceptions.TestFailedException: Some({"stdout":"PING google.com (172.217.5.238): 56 data bytes\n","stderr":"ping: permission denied (are you root?)\n"}) was not equal to Some({"stderr":"ping: icmp open socket: Operation not permitted\n","stdout":""})
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at system.basic.WskActionTests$$anonfun$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$34.apply(WskActionTests.scala:269)
	at system.basic.WskActionTests$$anonfun$7$$anonfun$apply$mcV$sp$7$$anonfun$apply$34.apply(WskActionTests.scala:268)
	at common.WskTestHelpers$$anonfun$withActivation$1.apply$mcV$sp(WskTestHelpers.scala:272)
```

Activation response

```json
{
  "duration": 276,
  "name": "ping",
  "subject": "guest",
  "activationId": "6fc4f220c3c842c484f220c3c852c4b0",
  "publish": false,
  "annotations": [
    {
      "key": "path",
      "value": "guest/ping"
    },
    {
      "key": "waitTime",
      "value": -15999
    },
    {
      "key": "kind",
      "value": "nodejs:6"
    },
    {
      "key": "limits",
      "value": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10
      }
    },
    {
      "key": "initTime",
      "value": 236
    }
  ],
  "version": "0.0.1",
  "response": {
    "result": {
      "stdout": "PING google.com (172.217.5.238): 56 data bytes\n",
      "stderr": "ping: permission denied (are you root?)\n"
    },
    "success": true,
    "status": "success"
  },
  "end": 1536587099497,
  "logs": [
    "2018-09-10T13:44:59.463416166Z stdout: Pinging to google.com",
    "2018-09-10T13:44:59.495845721Z stdout: stdout PING google.com (172.217.5.238): 56 data bytes",
    "2018-09-10T13:44:59.495859034Z stdout: ",
    "2018-09-10T13:44:59.495862754Z stdout: stderr ping: permission denied (are you root?)",
    "2018-09-10T13:44:59.495866021Z stdout: "
  ],
  "start": 1536587099221,
  "namespace": "guest"
}
```

### PR DESCRIPTION
**Pull request by chetanmeh**
As discussed on #4013 the test now asserts on absence of successful ping response

Fixes #4013 

## Related issue and scope

- [x] I opened an issue to propose and discuss this change (#4013)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [ ] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [x] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [x] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [x] I signed an [Apache CLA](https://github.com/apache/incubator-openwhisk/blob/master/CONTRIBUTING.md).
- [x] I reviewed the [style guides](https://github.com/apache/incubator-openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [x] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

File: tests/src/test/scala/system/basic/WskActionTests.scala [hunk 1]
```diff
@@ -266,8 +266,8 @@ class WskActionTests extends TestHelpers with WskTestHelpers with JsHelpers with
 
     val run = wsk.action.invoke(name, Map("payload" -> "google.com".toJson))
     withActivation(wsk.activation, run) { activation =>
-      activation.response.result shouldBe Some(
-        JsObject("stderr" -> "ping: icmp open socket: Operation not permitted\n".toJson, "stdout" -> "".toJson))
+      val stdout = activation.response.result.get.fields("stdout").convertTo[String]
+      stdout should not include ("bytes from")
```
Comment (markusthoemmes) [inline tests/src/test/scala/system/basic/WskActionTests.scala]: Good one! Should we also add should include("0 packets received") and should include("100% packet loss")?

Comment (chetanmeh) [reply tests/src/test/scala/system/basic/WskActionTests.scala]: In our case the response is 

```
"response": {
    "result": {
      "stdout": "PING google.com (172.217.5.238): 56 data bytes\n",
      "stderr": "ping: permission denied (are you root?)\n"
    },
    "success": true,
    "status": "success"
  }
```

So due to permission check process probably gets killed and it cannot report further about stats

Comment (markusthoemmes) [reply tests/src/test/scala/system/basic/WskActionTests.scala]: Maybe checking the return code to be non-zero is worthwhile as well?

Comment (chetanmeh) [reply tests/src/test/scala/system/basic/WskActionTests.scala]: Makes sense. Now capturing the process exit code and asserting against that as well

File: tests/src/test/scala/system/basic/WskActionTests.scala [hunk 2]
```diff
@@ -266,8 +266,13 @@ class WskActionTests extends TestHelpers with WskTestHelpers with JsHelpers with
...
     val run = wsk.action.invoke(name, Map("payload" -> "google.com".toJson))
     withActivation(wsk.activation, run) { activation =>
-      activation.response.result shouldBe Some(
-        JsObject("stderr" -> "ping: icmp open socket: Operation not permitted\n".toJson, "stdout" -> "".toJson))
+      val result = activation.response.result.get
+      result.getFields("stdout", "code") match {
+        case Seq(JsString(stdout), JsNumber(code)) =>
+          stdout should not include "bytes from"
+          code.intValue() should not be 0
+        case _ => fail()
```
Comment (markusthoemmes) [inline tests/src/test/scala/system/basic/WskActionTests.scala]: Please include a speaking message here, like `s"fields 'stdout' or 'code' where not of the expected format, was ${activation.response.result.get}"` if that makes sense.
