### PR TITLE
Send active ack on failed activations

### LINKED ISSUE #1906: sequences silently fail when internal invocations exceed 1MB threshold
in a sequence ABC, if B returns a payload > 1MB, the sequence fails (as it should), but with no indication as to why

### LINKED ISSUE #2118: controller should slow poll the DB for activations
Today there was an issue where an active ack message could not be produced because the result of the activation was too large. Even though the action finished quickly, the invoker still waited the (newly increased) 60s active ack timeout period. In the meantime, the controller converted this activation to non-blocking for having exceeded the 60 second blocking threshold (because polling throws `BlockingInvokeTimeout`). However, even though the action completed rather quickly, and the activation was written to the DB even before the active ack time expired, the user still had to wait 60 seconds just to find out that their activation was converted to non-blocking (when really it was already completed).

One solution is to have the controller simultaneously poll the DB for the activation, even during the initial active ack period. In this way, the controller can fail over to getting the activation from the DB without necessarily waiting the entire active ack expiration period.

Because this is more of a failover procedure (rather than a performance optimization) the polling could be done relatively slowly (500ms - 1000ms) to limit the amount of load placed on the DB.

### LINKED ISSUE #2324: Many "Message length exceeded" from a subject will result in lock out (for that subject)
## Environment details:

* Ubuntu 14.04.5 LTS
* Docker version 1.12.0, build 8eab29e
* ansible 2.1.2.0

## Steps to reproduce the issue:

1.   Invoke an Action which returns a message that exceeds the 1MB limit. Observe that even if you invoke it as "blocking" and the invocation is short, you will wait until timeout and receive only the Activation ID in the response. Get the Activation, observe that the duration is short in spite of the long wait. 
2.   Repeat step 1 (invoke as non-blocking or you'll be waiting a very long time) until you get the error "Too many requests for namespace". Check those Activations and verify that they have completed with the "message length exceeded maximum" error.
3.   Wait a few minutes (or any arbitrary length of time) and try an Action invocation. Observe that you still get the "Too many requests" error, even though none of the requests you made in step 2 are still in flight.

## Provide the expected results and outputs:

The result I would expect is that in step 1, a "message length exceeded" error is returned to the caller, and in step 3, "Too many requests" would either not occur (because they're quickly being completed, not still in-flight), or would go away after a short time.

## Provide the actual results and outputs:

Blocking invocations only return the Activation ID after a timeout, and the OW instance becomes locked with "Too many requests". This seems like a Denial of Service vulnerability as well.

## Code Samples
break-openwhisk.js:
```
exports.main = (args) => {
    let bigstring = "";
    for (let i = 0; i < 5000000; i++) {
        bigstring += "A";
    }
    return { bigstring: bigstring, message: "Should have failed" };
};
```
spam.sh:
```
#!/bin/bash

for i in {1..200}
do
    echo "invocation #$i..."
    wsk action invoke -iv break-openwhisk
    sleep 1
done
```

### PR DESCRIPTION
**Pull request by rabbah**
Fixes an active ack accounting bug in the load balancer for certain failed activations (where the invoker previously did not send an ack for the completed (but failed) activation. 

Fixes #2118.
Fixes #2324.
Fixes #1906.

### CODE REVIEW

File: core/controller/src/main/scala/whisk/core/controller/WebActions.scala [hunk 1]
```diff
@@ -551,12 +551,12 @@ trait WhiskWebActionsApi
     }
 
     private def completeRequest(
-        queuedActivation: Future[(ActivationId, Option[WhiskActivation])],
+        queuedActivation: Future[Either[ActivationId, WhiskActivation]],
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/controller/WebActions.scala]: Nice one :+1:

File: core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala [hunk 2]
```diff
@@ -121,46 +123,36 @@ class LoadBalancerService(config: WhiskConfig, entityStore: EntityStore)(implici
...
-        logging.info(this, s"received active ack for '$aid' (forced = $forced)")(tid)
+    private def processCompletion(aid: ActivationId, tid: TransactionId, response: Option[WhiskActivation]): Unit = {
         activationById.remove(aid) match {
             case Some(entry @ ActivationEntry(_, subject, invokerIndex, _, p)) =>
+                logging.info(this, s"received active ack for '$aid' (forced = ${response.isEmpty})")(tid)
                 activationByInvoker.getOrElseUpdate(invokerIndex, new TrieSet[ActivationEntry]).remove(entry)
                 activationBySubject.getOrElseUpdate(subject, new TrieSet[ActivationEntry]).remove(entry)
-                response.foreach(p.trySuccess(_))
-                logging.info(this, s"processed active response for '$aid'")(tid)
+                p.trySuccess(response.map(Right(_)).getOrElse(Left(aid)))
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/loadBalancer/LoadBalancerService.scala]: There is: `opt.toRight({{leftValue}}`, so in this case: `p.trySuccess(response.toRight(aid))`

File: core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala [hunk 3]
```diff
@@ -102,95 +106,101 @@ protected[actions] trait PrimitiveActions {
...
+                            // complete the future, which in turn will poison pill this scheduler
+                            activation => p.trySuccess(Right(activation.withoutLogs)) // Logs always not provided on blocking call
+                        } andThen {
+                            case Failure(e: NoDocumentException) => // do nothing, scheduler will reschedule another poll
+                            case Failure(t: Throwable) => // something went wrong, abort
+                                logging.error(this, s"failed while waiting on result: ${t.getMessage}")
+                                p.tryFailure(t) // complete the future, which in turn will poison pill this scheduler
+                        }
+
+                    case _ => throw new Exception("activation completed") // will halt the scheduler
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala]: Why not send a `PoisonPill` to self? Is this also the reason why logLevel is set to Info?

Comment (rabbah) [inline core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala]: for benefit of others the future doesn't have a reference to containing actor.

File: core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala [hunk 4]
```diff
@@ -107,10 +109,20 @@ class InvokerReactive(
...
+            val msg = CompletionMessage(transid, res, this.name)
+            producer.send("completed", msg).andThen {
+                case Success(_) =>
+                    logging.info(this, s"posted ${if (recovery) "recovery" else ""} completion of activation ${activationResult.activationId}")
+            }
+        }
+
+        send(Right(activationResult)).onFailure {
+            case t if t.getCause.isInstanceOf[RecordTooLargeException] =>
+                send(Left(activationResult.activationId), recovery = true)
```
Comment (markusthoemmes) [inline core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala]: Does this preserve InvokerHealth behavior which I think inspects the response-code of the message to determine healthyness?

Should we try to keep the old interface `WhiskActivation` and instead back off by sending it without the result? (but including the statuscode).

File: core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala [hunk 5]
```diff
@@ -94,7 +94,7 @@ case object ActivationCompleted
  */
 class ContainerProxy(
     factory: (TransactionId, String, ImageName, Boolean, ByteSize) => Future[Container],
-    sendActiveAck: (TransactionId, WhiskActivation) => Future[Any],
+    sendActiveAck: (TransactionId, WhiskActivation) => Unit,
```
Comment (markusthoemmes) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala]: Why don't we preserve the interface here? I know it's unused but why change it if not needed?

File: core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala [hunk 6]
```diff
@@ -102,95 +107,137 @@ protected[actions] trait PrimitiveActions {
...
-                    logging.error(this, s"[POST] action activation failed while waiting on result: ${t.getMessage}")
-                    promise.tryFailure(t)
-            }
-        } else {
-            logging.info(this, s"[POST] action activation timed out, terminated polling for result")
+        promise: Promise[Either[ActivationId, WhiskActivation]])(
+            implicit transid: TransactionId) extends Actor {
+
+        // when the future completes, self-destruct
+        promise.future.andThen { case _ => shutdown }
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala]: please add `()` to `shutdown` to indicate the sideeffect.

File: core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala [hunk 7]
```diff
@@ -102,95 +107,137 @@ protected[actions] trait PrimitiveActions {
...
-     * Polls for activation record. It is assumed that an activation record is created atomically and never updated.
-     * Fetch the activation record by its id. If it exists, complete the promise. Otherwise recursively poll until
-     * either there is an error in the get, or the promise has completed because it timed out. The promise MUST
-     * complete in the caller to terminate the polling.
-     */
-    private def pollDbForResult(
-        docid: DocId,
+    /** Periodically polls the db to cover missing active acks. */
+    val datastorePollPeriodForActivation = 15.seconds
+    val datastorePreemtivePolling = Seq(1.second, 3.seconds, 5.seconds, 7.seconds)
```
Comment (markusthoemmes) [inline core/controller/src/main/scala/whisk/core/controller/actions/PrimitiveActions.scala]: Typo (preemPtive)

File: core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala (hunk 5 above)
Comment (rabbah) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerProxy.scala]: Heh, because it's unused. I'll revert if you prefer.

File: core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala (hunk 4 above)
Comment (rabbah) [inline core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala]: You'll see this later. I think it is ok in that it's a recovery for a specific failure case not all Kafka errors.

Comment (markusthoemmes) [inline core/invoker/src/main/scala/whisk/core/invoker/InvokerReactive.scala]: Edit: I see, the Controller would complete via db polling if I read it correctly?

**Comment by rabbah** [comment]
pg3/761 approved.

**Comment by rabbah** [comment]
Also pg2/1727 🔵
