### PR TITLE
Fix parsing of application-json content type.

### LINKED ISSUE #2764: Setting content-type with no body results in malformed error
When I set the `content-type` header on a web action, it fails if there's no body with the message:

> {"error":"The request content was malformed:\nUnexpected end-of-input at input index 0 (line 1, position 1), expected JSON Value:\n\n^\n","code":5174826}

```bash
# No headers
$ curl https://openwhisk.eu-gb.bluemix.net/api/v1/web/19FT_demo/default/hello.json
{
  "msg": "Hello World"
}

# Content-Type header
$ curl -H "content-type: application/json" https://openwhisk.eu-gb.bluemix.net/api/v1/web/19FT_demo/default/hello.json
{"error":"The request content was malformed:\nUnexpected end-of-input at input index 0 (line 1, position 1), expected JSON Value:\n\n^\n","code":5174826}

# Content-Type header and an empty body
$ curl -H "content-type: application/json" -d "{}" https://openwhisk.eu-gb.bluemix.net/api/v1/web/19FT_demo/default/hello.json
{
  "msg": "Hello World"
}
```

### PR DESCRIPTION
**Pull request by rabbah**
Do not fail with content-type is set but the entity is empty. Also extend handling of application-json content to permit first class values e.g., array wont be base64 encoded.

Closes #2764.
FYI @akrabat.

### CODE REVIEW

File: tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala [hunk 1]
```diff
@@ -488,6 +488,30 @@ trait WebActionsApiTests extends ControllerTestCommon with BeforeAndAfterEach wi
       }
     }
 
+    it should s"invoke action which receives an empty entity (auth? ${creds.isDefined})" in {
```
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/controller/test/WebActionsApiTests.scala]: This test will have to be updated once https://github.com/apache/incubator-openwhisk/pull/2741/files is merged. Will have to add ```headers = List(`Content-Type`(ContentTypes.`application/json`))``` to `metaPayload`.

**Comment by rabbah** [comment]
PG1/2070 🚀

**Comment by rabbah** [comment]
PG1/2070 🔵
