### PR TITLE
To resolve #2245 - optimize container removal

### LINKED ISSUE #2245: new ContainerPool aggressively restarts containers under load
## Environment details:

* local deployment, Mac OS
* docker 17.03 (server 17.05 on docker-machine) 

## Steps to reproduce the issue:

1.   use [https://github.com/markusthoemmes/openwhisk-performance] to run throughput test (tests/throughput.sh)
2.   run throughput test: 
```./throughput.sh https://192.168.99.100  "$(cat ~/git/forks/tysonnorris/openwhisk/ansible/files/auth.guest)" 10 1000```
3.   in a separate terminal check for nodesjsaction containers - notice they are constantly recreated
```docker ps | grep nodejs```

## Provide the expected results and outputs:

Expected: Don't restart containers when scheduling activation for an action that already has max warm containers that are all busy. Instead, requeue the activation for later.

## Provide the actual results and outputs:

1. Per above, notice the containers are restarting constantly, even though there is only a single action being exercised

2. Notice throughput latency is way up, compared to 4 concurrent users. 
```
[Mon May 15 2017 20:24:41 GMT+0000 (UTC)] INFO Requests: 0 (0%), requests per second: 0, mean latency: 0 ms
[Mon May 15 2017 20:24:46 GMT+0000 (UTC)] INFO Requests: 10 (1%), requests per second: 2, mean latency: 2904.3 ms
[Mon May 15 2017 20:24:51 GMT+0000 (UTC)] INFO Requests: 20 (2%), requests per second: 2, mean latency: 4631.8 ms
[Mon May 15 2017 20:24:56 GMT+0000 (UTC)] INFO Requests: 28 (3%), requests per second: 2, mean latency: 4242.9 ms
[Mon May 15 2017 20:25:01 GMT+0000 (UTC)] INFO Requests: 36 (4%), requests per second: 2, mean latency: 5887.2 ms
[Mon May 15 2017 20:25:06 GMT+0000 (UTC)] INFO Requests: 50 (5%), requests per second: 3, mean latency: 5270.4 ms
[Mon May 15 2017 20:25:11 GMT+0000 (UTC)] INFO Requests: 60 (6%), requests per second: 2, mean latency: 4091.2 ms
[Mon May 15 2017 20:25:16 GMT+0000 (UTC)] INFO Requests: 70 (7%), requests per second: 2, mean latency: 4556.8 ms
[Mon May 15 2017 20:25:21 GMT+0000 (UTC)] INFO Requests: 84 (8%), requests per second: 3, mean latency: 4444.2 ms
[Mon May 15 2017 20:25:26 GMT+0000 (UTC)] INFO Requests: 94 (9%), requests per second: 2, mean latency: 4195.4 ms
```

## Additional information you deem important:
n/a

### PR DESCRIPTION
**Pull request by tysonnorris**
Resolves #2245
Only remove a running container to make room for activation in a max'ed out ContainerPool IFF a) the running container is in "Free" state and b) the running container is a DIFFERENT action than the incoming activation

### CODE REVIEW

**Comment by tysonnorris** [comment]
Need to fix some tests...

File: core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala [hunk 1]
```diff
@@ -192,13 +192,14 @@ object ContainerPool {
      * takes away one of their containers iff the namespace placing the new job is
      * not already the most consuming one.
      *
-     * @param namespace the namespace that wants to get a container
+     * @param action the action that wants to get a container
      * @param pool a map of all containers in the pool
      * @return a container to be removed iff found
      */
-    def remove[A](invocationNamespace: EntityName, pool: Map[A, WorkerData]): Option[A] = {
+    def remove[A](action: ExecutableWhiskAction, pool: Map[A, WorkerData]): Option[A] = {
```
Comment (rabbah) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: shouldn't this be predicated on both the subject and the action name?

Comment (tysonnorris) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: I thought the container should be reusable across same actions regardless of subject?

Comment (rabbah) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: containers are specific to a subject+action; we don't reuse a container to run an action for more than one subject since we assume the container is tainted (ok to self taint but shall not taint another user or action).

Comment (tysonnorris) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: I see, will take a look after I fix the tests

Comment (tysonnorris) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: @rabbah I don't see this (isolation by subject) implemented the new ContainerPool currently, I expect it would need to be added to WarmedData - should I add that as part of this PR, or separate?

Comment (rabbah) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: See ContainerPool.schedule.

Comment (tysonnorris) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: oh...sorry, was mixing up user namespace and action namespace... will update to address this

Comment (rabbah) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: heh, I had suggested retyping that to `Identity` so it's more obvious.

File: core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala [hunk 2]
```diff
@@ -192,13 +192,15 @@ object ContainerPool {
...
+     * @param invocationNamespace the namespace, that wants to run the action
      * @param pool a map of all containers in the pool
      * @return a container to be removed iff found
      */
-    def remove[A](invocationNamespace: EntityName, pool: Map[A, WorkerData]): Option[A] = {
+    def remove[A](action: ExecutableWhiskAction, invocationNamespace: EntityName, pool: Map[A, WorkerData]): Option[A] = {
+        //try to find a Free container that is initialized with any OTHER action
         val grouped = pool.collect {
-            case (ref, WorkerData(w: WarmedData, _)) => ref -> w
+            case (ref, WorkerData(w: WarmedData, Free)) if (w.action != action || w.invocationNamespace != invocationNamespace) => ref -> w
```
Comment (markusthoemmes) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: Do we want to only collect `Free` containers? I'd claim no, since the calculation below searches for the most consuming namespace. If that namespace is inducing very high load, it can still monopolize the system if we are not able to claim containers back because that namespace having only `Busy` containers all the time.

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 3]
```diff
@@ -148,11 +169,43 @@ class ContainerPoolTests extends TestKit(ActorSystem("ContainerPool"))
...
+      containers(0).expectMsg(runMessage)
+      containers(0).send(pool, NeedWork(warmedData()))
+      feed.expectMsg(ContainerReleased)
+      pool ! runMessage1b
+      containers(0).expectMsg(Remove)
+      containers(1).expectMsg(runMessage1b)
+    }
+
+
+    it should "not remove a container to make space in the pool if it is already full and the same action + same invocation namespace arrives" in within(timeout) {
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: This test is essentially a duplicate of the below, no? I think we shouldn't test the internals of `schedule` and `remove` too much in the more general `ContainerPoolTests`. Thoughts?

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 4]
```diff
@@ -78,8 +81,26 @@ class ContainerPoolTests extends TestKit(ActorSystem("ContainerPool"))
         ActivationId(),
         invocationNamespace.toPath,
         None)
+    val messageb = ActivationMessage(
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Can we give those more meaningful names? Like `differentNamespaceMessage` and `differentMessage`?

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 5]
```diff
@@ -68,7 +69,9 @@ class ContainerPoolTests extends TestKit(ActorSystem("ContainerPool"))
     val memoryLimit = 256.MB
 
     val invocationNamespace = EntityName("invocationSpace")
+    val invocationNamespace2 = EntityName("invocationSpace2")
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Would a more speaking name make sense? Like `differentInvocatioNamespace`?

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 6]
```diff
@@ -68,7 +69,9 @@ class ContainerPoolTests extends TestKit(ActorSystem("ContainerPool"))
...
     val action = ExecutableWhiskAction(EntityPath("actionSpace"), EntityName("actionName"), exec)
+    val action2 = ExecutableWhiskAction(EntityPath("actionSpace"), EntityName("actionName2"), exec)
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Same comment on naming. You can also write:

```
val differentAction = action.copy(name = EntityName("actionName2"))
```

Makes it a bit more apparent that you just change the name.

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 7]
```diff
@@ -78,8 +81,26 @@ class ContainerPoolTests extends TestKit(ActorSystem("ContainerPool"))
...
+      action2.fullyQualifiedName(true),
+      action2.rev,
+      Identity(Subject(), invocationNamespace2, AuthKey(), Set()),
+      ActivationId(),
+      invocationNamespace2.toPath,
+      None)
 
     val runMessage = Run(action, message)
+    val runMessage1b = Run(action, messageb)
+    val runMessage2 = Run(action2, message2)
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Same comment on naming.

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 8]
```diff
@@ -365,7 +430,7 @@ class ContainerPoolObjectTests extends FlatSpec with Matchers with MockFactory {
             'second -> freeWorker(second),
             'oldest -> freeWorker(oldest))
 
-        ContainerPool.remove(EntityName(commonNamespace), pool) shouldBe Some('oldest)
+        ContainerPool.remove(first.action, EntityName("anyNamespace"), pool) shouldBe Some('oldest)
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Should use `createAction()`. The relationship to the first warmed data is not necessary here.

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 9]
```diff
@@ -381,6 +446,6 @@ class ContainerPoolObjectTests extends FlatSpec with Matchers with MockFactory {
             'largeYoung -> freeWorker(warmedData(namespace = largeNamespace, lastUsed = Instant.ofEpochMilli(3))),
             'largeOld -> freeWorker(warmedData(namespace = largeNamespace, lastUsed = Instant.ofEpochMilli(2))))
 
-        ContainerPool.remove(myData.invocationNamespace, pool) shouldBe Some('largeOld)
+        ContainerPool.remove(myData.action, EntityName("anyNamespace"), pool) shouldBe Some('largeOld)
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Same comment as above. Could use `createAction()` as there is no direct relationship to the data.

**Comment by markusthoemmes** [comment]
Thank you so much for finding and fixing this. Great job! 🎉 
Would you please install our formatter for scala (located here: https://github.com/apache/incubator-openwhisk/tree/master/tools/eclipse) so we have consistent spacing in place.

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala [hunk 10]
```diff
@@ -20,6 +20,7 @@ import java.time.Instant
 
 import scala.collection.mutable
 import scala.concurrent.duration._
+import scala.language.postfixOps
```
Comment (markusthoemmes) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: You'll come to hate `postfixOps` very soon because it induces strange compilation behavior. Personally I avoid it alltogether.

**Comment by markusthoemmes** [comment]
PG1 1540 🔵

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala (hunk 4 above)
Comment (tysonnorris) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: Thanks for the updates, and the tips!

File: tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala (hunk 3 above)
Comment (tysonnorris) [inline tests/src/test/scala/whisk/core/containerpool/test/ContainerPoolTests.scala]: below test ends with exectNoMsg() instead of expectMsg() - testing cases where removal result is expected to be None vs Some based on whether this is a different action/invocation namespace

File: core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala (hunk 2 above)
Comment (tysonnorris) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: I see, yes Free and Busy should be collected, BUT only Free should be eligible for removal - it looks like current impl would allow a Busy to be removed, although unlikely since the lastUsed should be recent.

Comment (markusthoemmes) [inline core/invoker/src/main/scala/whisk/core/containerpool/ContainerPool.scala]: No, actually Busy should be removed as well.
