### PR TITLE
fix ansible install errors in vagrant

### LINKED ISSUE #2901: vagrant error in cryptography setup command
## Environment details:

* vagrant
* MacOS

## Steps to reproduce the issue:

1.   Follow steps in README https://github.com/apache/incubator-openwhisk#quick-start
```
# Clone openwhisk
git clone --depth=1 https://github.com/apache/incubator-openwhisk.git openwhisk

# Change directory to tools/vagrant
cd openwhisk/tools/vagrant

# Run script to create vm and run hello action
./hello
```
2.  Walk outside smell the roses and have a coffee  

## Provide the expected results and outputs:

```
wsk action invoke /whisk.system/utils/echo -p message hello --result
{
    "message": "hello"
}
```

## Provide the actual results and outputs:

```
==> default:     warning: no previously-included files found matching '.travis/install.sh'
==> default:     warning: no previously-included files found matching '.travis/run.sh'
==> default:     warning: no previously-included files found matching '.coveragerc'
==> default:     warning: no previously-included files found matching 'tasks.py'
==> default: Downloading/unpacking cryptography>=1.5 (from paramiko->ansible==2.3.0.0)
==> default:   Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
==> default:     error in cryptography setup command: Invalid environment marker: python_version < '3'
==> default:     Complete output from command python setup.py egg_info:
==> default:     error in cryptography setup command: Invalid environment marker: python_version < '3'
==> default:
==> default: ----------------------------------------
==> default: Cleaning up...
==> default: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
==> default: Storing debug log for failure in /home/vagrant/.pip/pip.log
```

## Additional information you deem important:
* Google error and found out fix is to `sudo pip install --upgrade setuptools` from https://github.com/ansible/ansible/issues/31741

Related to PR #2891

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #2901

Related to #2891 

Fix to ansible error with crypto is `sudo pip install --upgrade setuptools`

We have mismatch version of scala, update to match `2.8.11`

Try using an official ubuntu 14 image from provider virtual box

Ubuntu 14 is LTS until April 2019 according to this site: https://wiki.ubuntu.com/Releases

So I proposed we keep using Ubuntu trusty, since it's the version we use CI/CD in Travis

### CODE REVIEW

File: tools/ubuntu-setup/scala.sh [hunk 1]
```diff
@@ -2,7 +2,7 @@
 set -e
 set -x
 
-wget www.scala-lang.org/files/archive/scala-2.11.6.deb -O /tmp/scala-2.11.6.deb
-sudo dpkg -i /tmp/scala-2.11.6.deb
+wget www.scala-lang.org/files/archive/scala-2.11.8.deb -O /tmp/scala-2.11.8.deb
+sudo dpkg -i /tmp/scala-2.11.8.deb
```
Comment (markusthoemmes) [inline tools/ubuntu-setup/scala.sh]: I think we can throw this out of the setup. Gradle should grab the scala compiler dynamically.
