### PR TITLE
Limit length of HTTP body displayed when debugging.

### LINKED ISSUE #928: Limit amount of HTTP body displayed to stdout when -d option is used
## Environment details:
- Any
## Steps to reproduce the issue:
1.   create a large file (50 MB) called bigfile.js.  The file does not have to be valid JavaScript
2.   `wsk action create bigfile bigfile.js -d`
## Provide the expected results and outputs:

Display a subset of the HTTP body (i.e. subset of the script file).
## Provide the actual results and outputs:

Too much output id dumped to the display.  The terminal may also hang
## Additional information you deem important:
- May also need to consider handling binary vs text files differently as well.

### PR DESCRIPTION
**Pull request by bpoole16**
This aims to limit the length of HTTP body displayed to stdout when -d option is used. Closes #928

### CODE REVIEW

**Comment by bpoole16** [comment]
@mdeuser Let me know if this is what you were thinking.

File: tests/src/test/scala/system/basic/WskBasicTests.scala [hunk 1]
```diff
@@ -492,6 +492,21 @@ class WskBasicTests
...
     }
 
+    it should "create an action and limit the length of req body in the debug to 1000 bytes" in {
+            val file = Some(TestUtils.getTestActionFilename("largeFile.js"))
+            val actionName = "largeFileAction"
+            val msg = "Req Body excedes 1000 bytes and will be truncated"
+            val output = "fWbADPnp\"" //   Ending substring of truncated output
+
+            try {
+                val action = wsk.action.create(name = actionName, artifact = file, expectedExitCode = SUCCESS_EXIT, debug = Some(true)).stdout
```
Comment (dubeejw) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: Should be able to use `assetHelper.withCleaner` here.

File: tests/src/test/scala/system/basic/WskBasicTests.scala [hunk 2]
```diff
@@ -492,6 +492,21 @@ class WskBasicTests
...
+                action should include(output)
+                action should include(msg)
+            } finally {
+                val delAction = wsk.action.delete(name = actionName, expectedExitCode = DONTCARE_EXIT)
```
Comment (dubeejw) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: Use the built-in cleaner instead. We would need the exit code to be successful value. Otherwise, some other test may try to create an action with the same name you are using and fail if this action wasn't actually deleted.

File: tests/dat/actions/largeFile.js [hunk 3]
```diff
@@ -0,0 +1,11 @@
+function main (params) {
+    var name = params.payload || "User";
+    var list = "L69lhnfnD1rjFoesRquHOIXHAMR3cYp8pVxfag38WNHn6ijlyEn7r5VsNlM6kvZQHje6q6nTV5Wts3wwG6NqQGVllPm5bH6cFnburN2UwRIZrVVK9lPXTlL0YmZbpKQaTilpiXhnQH2RwRGEtzK2Puos\n" +
```
Comment (dubeejw) [inline tests/dat/actions/largeFile.js]: Can this list be generated programmatically?

File: tools/cli/go-whisk/whisk/client.go [hunk 4]
```diff
@@ -211,14 +211,31 @@ func (c *Client) addAuthHeader(req *http.Request, authRequired bool) error {
     }
     return nil
 }
-
+//Limiter limits the size of 'Req Body (ASCII quoted string)' output for the debugger ONLY.
+//Returns truncated req body, reloaded io reader and errors.
+func limiter(body io.ReadCloser) (string, io.ReadCloser, error) {
```
Comment (dubeejw) [inline tools/cli/go-whisk/whisk/client.go]: Maybe use a more descriptive function name (bodyLimiter).

File: tests/dat/actions/largeFile.js (hunk 3 above)
Comment (bpoole16) [inline tests/dat/actions/largeFile.js]: I need to fill the text file with around 1000 or more bytes that is why it is hard coded.

Comment (dubeejw) [inline tests/dat/actions/largeFile.js]: Could do something like this var list = "a".repeat(1000)` or `var list = Array(1000).join("a")`.

Comment (dubeejw) [inline tests/dat/actions/largeFile.js]: @bpoole16, I see your testing on action create. The above would only work on invoke.

File: tests/src/test/scala/system/basic/WskBasicTests.scala (hunk 2 above)
Comment (bpoole16) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: I was trying to but wasn't sure how to get stdout of a action.create with asset-cleaner.

File: tests/src/test/scala/system/basic/WskBasicTests.scala [hunk 5]
```diff
@@ -496,14 +496,14 @@ class WskBasicTests
...
 
             try {
                 val action = wsk.action.create(name = actionName, artifact = file, expectedExitCode = SUCCESS_EXIT, debug = Some(true)).stdout
-                action should include(output)
+                action should include regex(output)
                 action should include(msg)
             } finally {
-                val delAction = wsk.action.delete(name = actionName, expectedExitCode = DONTCARE_EXIT)
+                val delAction = wsk.action.delete(name = actionName, expectedExitCode = SUCCESS_EXIT)
             }
```
Comment (bpoole16) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: Wasn't able to get `.stdout` to work with asset-cleaner, if anyone has any ideas please let me know.

File: tests/src/test/scala/system/basic/WskBasicTests.scala [hunk 6]
```diff
@@ -496,14 +496,14 @@ class WskBasicTests
...
             val msg = "Req Body excedes 1000 bytes and will be truncated"
-            val output = "fWbADPnp\"" //   Ending substring of truncated output
+            val output = "[A-Za-z1-9{25}]\"".r  //   Ending substring of truncated output
 
             try {
                 val action = wsk.action.create(name = actionName, artifact = file, expectedExitCode = SUCCESS_EXIT, debug = Some(true)).stdout
-                action should include(output)
+                action should include regex(output)
                 action should include(msg)
             } finally {
```
Comment (bpoole16) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: Wasn't able to get .stdout to work with asset-cleaner, if anyone has any ideas please let me know.

File: tests/src/test/scala/system/basic/WskBasicTests.scala [hunk 7]
```diff
@@ -492,6 +492,21 @@ class WskBasicTests
...
     }
 
+    it should "create an action and limit the length of req body in the debug to 1000 bytes" in {
+            val file = Some(TestUtils.getTestActionFilename("largeFile.js"))
+            val actionName = "largeFileAction"
+            val msg = "Req Body excedes 1000 bytes and will be truncated"
+            val output = "[A-Za-z1-9{25}]\"".r  //   Ending substring of truncated output
+
+            try {
+                val action = wsk.action.create(name = actionName, artifact = file, expectedExitCode = SUCCESS_EXIT, debug = Some(true)).stdout
```
Comment (bpoole16) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: Having trouble getting assest-cleaner to work with action.create(xxx).stdout. Any ideas would be much appreciated.

Comment (mdeuser) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: Is stdout needed here?  I think it will be the wsk.action.invoke stdout that is being tested for truncation..

File: tests/dat/actions/largeFile.js (hunk 3 above)
Comment (rabbah) [inline tests/dat/actions/largeFile.js]: we have an action that can do this already - see the action limit tests.

File: tests/src/test/scala/common/Wsk.scala [hunk 8]
```diff
@@ -299,7 +299,8 @@ class WskAction()
         shared: Option[Boolean] = None,
         update: Boolean = false,
         web: Option[String] = None,
-        expectedExitCode: Int = SUCCESS_EXIT)(
+        expectedExitCode: Int = SUCCESS_EXIT,
+        debug: Option[Boolean] = None)(
```
Comment (rabbah) [inline tests/src/test/scala/common/Wsk.scala]: do we really want to test cli debug here?

File: tests/src/test/scala/system/basic/WskBasicTests.scala [hunk 9]
```diff
@@ -492,6 +492,21 @@ class WskBasicTests
...
+                action should include regex(output)
+                action should include(msg)
+            } finally {
+                val delAction = wsk.action.delete(name = actionName, expectedExitCode = SUCCESS_EXIT)
```
Comment (rabbah) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: why assign a value that's not used.
also do not use create/delete instead use the asset cleaner.

File: tests/src/test/scala/system/basic/WskBasicTests.scala (hunk 7 above)
Comment (rabbah) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: @bpoole16 can you explain the issue?

**Comment by mdeuser** [comment]
@rabbah - this is a fix for limiting large http body data being dumped out when the --verbose or --debug flag is specified.

File: tests/src/test/scala/system/basic/WskBasicTests.scala (hunk 7 above)
Comment (bpoole16) [inline tests/src/test/scala/system/basic/WskBasicTests.scala]: The goal, from my understanding, is to limit the HTTP body during output of a debug/verbose. The only way I've been able to access this information is through stdout of a create, invoke doesn't seem to supply the correct req or response. This also leads to the question of whether I should be testing something that is in the debug/verbose.

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala [hunk 10]
```diff
@@ -269,4 +269,29 @@ class ActionLimitsTests extends TestHelpers with WskTestHelpers {
...
 
+    it should "limit the length of HTTP req/resp bodies for debug messages to 1000 bytes" in withAssetCleaner(wskprops) {
+        (wp, assetHelper) =>
+            val auth: Seq[String] = Seq("--auth", wskprops.authKey)
+            val name = "largeFileAction"
+            val debugMsg = "Body excedes 1000 bytes and will be truncated"
+            val bodyMsg = "ENDUNIQUE"   //  Message that should be truncated
+
+            val actionCode = new File(s"$testActionsDir${File.separator}$name.js")
+            actionCode.createNewFile()
```
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Why create the file for each test run instead of having one in `dat/actions`? You can use `echo.js` and send a large string as a parameter to it.

Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]:
```
val input = "a" * 1000
wsk.action.invoke(name, parameters = input)
```

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala [hunk 11]
```diff
@@ -269,4 +269,29 @@ class ActionLimitsTests extends TestHelpers with WskTestHelpers {
             }
     }
 
+    it should "limit the length of HTTP req/resp bodies for debug messages to 1000 bytes" in withAssetCleaner(wskprops) {
+        (wp, assetHelper) =>
+            val auth: Seq[String] = Seq("--auth", wskprops.authKey)
+            val name = "largeFileAction"
+            val debugMsg = "Body excedes 1000 bytes and will be truncated"
```
Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: so how would one check if the cli encoded a zip correctly? should debug continue to show the full content but not verbose? one or the other...

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala (hunk 10 above)
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Looks like the issue is for create, but your body limiter should limit all the received input?

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala (hunk 11 above)
Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: the reason i say debug is we have had situations where the debug response was useful to find problems with the CLI where the HTTP response is correct but the output of the CLI that's formatted for consumption isn't (due to scema mismatches).

I'm still puzzled by this change - why limit debug output at all.
Should there be an option to dump the output to a file at least?

Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: exceeds is mispelled.

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala (hunk 10 above)
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Or if you really want to test create, you can pass a big parameter to any of the existing files in `action/data`.
```
val input = Map("payload" -> JsString("a" * 1000))
assetHelper.withCleaner(wsk.action, name) {
                (action, _) => action.create(name, file, parameters = input)
            }
```

Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Are we okay with adding `--debug` to invoke or should I take the path of Seq() so I don't have to create a `--debug` variable?

Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: the latter - as the cli tests are moved to their own repository, this flag wont be relevant to the REST api implementation of the Wsk interface.

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala (hunk 11 above)
Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: From my understanding, maybe @mdeuser can elaborate more on this, we currently print out the req/resp body a total of 4 times (2 of those being debugs) during a `wsk action create xxx -d`. If you take a large file, the amount of output can overwhelm the CLI and even hang it.  Maybe this fixes something that is too rare to matter if there are more frequent disadvantages?

Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: so it is a problem that there are too many debug statements - rather than limiting the debug output, should there be deduping of debug messages?

Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Just to be clear, there is only 1 debug per body. For instance, req body has 1 debug and println and resp body has 1 debug and println - printing a total of 4 times.

Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: OK then I'm entirely confused.

Can you show an example before and after with desired effect?

Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Example of before and after for req body output of `wsk action create xxx -d`
limitexample

Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Right, you wouldn't be able to check if a request was encoded correctly. Maybe adding a flag to allow for truncation would be correct path to take?

Comment (rabbah) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Sounds like the debug flag to me - I'm not sure what truncating is buying us. Debug/Verbose is used sparingly.

Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: If there is a large file, let's say 1MB or larger, there is a great deal of data dumping onto the screen. A truncation could help limit this enormous amount of data being displayed to the user/developer. But in smaller cases, like you pointed out, it seems to hamper the results more than it helps. This is why I've been thinking of either creating a separate flag or a raising the cap from 1000 bytes.

It's true, this issue could be prevented by using verbose where only `req body` and `code` are displayed but there is a loss of important debug features here. Also, the original issue called for the implementation of truncation with debug which is why I proceeded down this path. Since debug/verbose is used so sparingly, that brings up a concern; how sparingly would someone use debug AND have a large file?

**Comment by rabbah** [comment]
the cli has two flags: verbose and debug right? how about verbose truncate and debug doesn't.

**Comment by bpoole16** [comment]
Will attempt to proceed in the direction of limiting verbose only and leaving the debug to print fully.

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala [hunk 12]
```diff
@@ -60,6 +60,26 @@ class ActionLimitsTests extends TestHelpers with WskTestHelpers {
 
     behavior of "Action limits"
 
+    it should "limit the length of HTTP req/resp bodies for debug messages to 1000 bytes" in withAssetCleaner(wskprops) {
```
Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Old test, need updating.

**Comment by bpoole16** [comment]
PG 4 #596 Passsed

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala [hunk 13]
```diff
@@ -60,6 +60,31 @@ class ActionLimitsTests extends TestHelpers with WskTestHelpers {
 
     behavior of "Action limits"
 
+    it should "limit the length of HTTP Req/Resp Body for --verbose to 1000 bytes" in withAssetCleaner(wskprops) {
```
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: This test is in the wrong file. ActionLimitTests are for action limits related to the RestAPI. Should move to WskBasicUsageTests.scala.

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala [hunk 14]
```diff
@@ -60,6 +60,31 @@ class ActionLimitsTests extends TestHelpers with WskTestHelpers {
...
+            val largeTestFile = new File(s"$testActionsDir${File.separator}$name.js")    // Creates a file to see if "code" field is limited
+
+            largeTestFile.createNewFile()
+            val pw = new PrintWriter(largeTestFile)
+            pw.write("a" * 1000)
+            pw.write(endMsg)
+            pw.close
+
+            assetHelper.withCleaner(wsk.action, name) {
+                (action, _) => wsk.action.create(name, Some(largeTestFile.getAbsolutePath))
```
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Did you try using the a large parameters argument instead of creating the big file for every run?

File: tools/cli/go-whisk/whisk/client.go [hunk 15]
```diff
@@ -222,14 +222,76 @@ func (c *Client) addAuthHeader(req *http.Request, authRequired bool) error {
...
+    if err != nil {
+        Verbose("ioutil.ReadAll(req.Body) error: %s\n", err)
+        werr := MakeWskError(err, EXITCODE_ERR_NETWORK, DISPLAY_MSG, NO_DISPLAY_USAGE)
+        return nil, body, werr
+    }
+    reload := ioutil.NopCloser(bytes.NewBuffer(data))
+    if len(data) > limit {
+        Verbose("Req Body excedes %d bytes and will be truncated\n", limit)
+        newData := string(data[:limit]) + buffer    // Must convert to string to add buffer otherwise malformed error will be thrown
+        return []byte(newData), reload, nil
```
Comment (dubeejw) [inline tools/cli/go-whisk/whisk/client.go]: Seems like an unneeded cast back to a byte array here since the data is just converted back to a string later.

File: tools/cli/go-whisk/whisk/client.go [hunk 16]
```diff
@@ -222,14 +222,76 @@ func (c *Client) addAuthHeader(req *http.Request, authRequired bool) error {
...
+    data, err := ioutil.ReadAll(body)
+    if err != nil {
+        Verbose("ioutil.ReadAll(req.Body) error: %s\n", err)
+        werr := MakeWskError(err, EXITCODE_ERR_NETWORK, DISPLAY_MSG, NO_DISPLAY_USAGE)
+        return nil, body, werr
+    }
+    reload := ioutil.NopCloser(bytes.NewBuffer(data))
+    if len(data) > limit {
+        Verbose("Req Body excedes %d bytes and will be truncated\n", limit)
+        newData := string(data[:limit]) + buffer    // Must convert to string to add buffer otherwise malformed error will be thrown
```
Comment (dubeejw) [inline tools/cli/go-whisk/whisk/client.go]: Not sure I see why a new line is added here when the data is being printing with `fmt.Println()`.

File: tools/cli/go-whisk/whisk/client.go [hunk 17]
```diff
@@ -222,14 +222,76 @@ func (c *Client) addAuthHeader(req *http.Request, authRequired bool) error {
...
+    limit := 1000    // 1000 byte limit, anything over is truncated
+    buffer := "\"\n    "    // Appended to the end of newData to keep correct formating
+    data, err := ioutil.ReadAll(body)
+    if err != nil {
+        Verbose("ioutil.ReadAll(req.Body) error: %s\n", err)
+        werr := MakeWskError(err, EXITCODE_ERR_NETWORK, DISPLAY_MSG, NO_DISPLAY_USAGE)
+        return nil, body, werr
+    }
+    reload := ioutil.NopCloser(bytes.NewBuffer(data))
+    if  bytes.Contains(data, []byte("\"code\":")) && bytes.Contains(data, []byte("\"binary\":")) {
```
Comment (dubeejw) [inline tools/cli/go-whisk/whisk/client.go]: Hmm, why only limit binary data?

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala (hunk 13 above)
Comment (dubeejw) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Does this test both respBodyLimiter and reqBodyLimiter?

File: tools/cli/go-whisk/whisk/client.go (hunk 17 above)
Comment (bpoole16) [inline tools/cli/go-whisk/whisk/client.go]: The goal is to limit the fields that are known to run long, this really only being the code field. I'm trying to figure out the best way to extract the code field and limit it and then reconstruct the output with the newly limited code field.

File: tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala (hunk 13 above)
Comment (bpoole16) [inline tests/src/test/scala/whisk/core/limits/ActionLimitsTests.scala]: Yes it does, the issue is other commands aren't working properly.

File: tools/cli/go-whisk/whisk/client.go (hunk 15 above)
Comment (bpoole16) [inline tools/cli/go-whisk/whisk/client.go]: I agree, was overthinking this part.

File: tools/cli/go-whisk/whisk/client.go (hunk 16 above)
Comment (bpoole16) [inline tools/cli/go-whisk/whisk/client.go]: I was trying to replicate the original output and without that buffer it does add a space between req body and `RESPONSE:Got response with code 200 `

File: tools/cli/go-whisk/whisk/client.go (hunk 15 above)
Comment (bpoole16) [inline tools/cli/go-whisk/whisk/client.go]: Ah, just remembered why I did that. If you just return a string then you would have to wrap data in string. It seems to be a pick your poison, wrap newData in a []byte or wrap data in a string.

**Comment by bpoole16** [comment]
@dubeejw Made some changes per your request, also let me know if I should convert to strings vs []byte.

**Comment by bpoole16** [comment]
To me this issue has gotten too specific. It's now only limiting in verbose for a certain field in resp body for actions only - feels off to me. The only "global" limiting in verbose is for req body.

**Comment by dubeejw** [comment]
What I noticed was that when I ran an action get for an action that has a big zip file attached to it, I still had to scroll through all the normal output before I could seen the truncated code in the verbose output. I think it'd be better to truncate the code in verbose and normal modes. @rabbah

**Comment by dubeejw** [comment]
@bpoole16, how about doing it this way? https://github.com/dubeejw/openwhisk/commit/5b57eb6ddd4b6d55a051f24f6e221b2fba944dd8

**Comment by bpoole16** [comment]
That works, I had something like that similar until I realized it was cutting off a bunch of resp information. Due to this I was just trying to find problematic fields and reduce them. If we are okay with losing resp body information looks fine to me.

File: docs/rest_api.md [hunk 18]
```diff
@@ -70,7 +70,9 @@ The OpenWhisk API supports request-response calls from web clients. OpenWhisk re
 ## Using the CLI verbose mode
 
 The OpenWhisk CLI is an interface to the OpenWhisk REST API.
-You can run the CLI in verbose mode with the flag `-v`, this will print all the information about the HTTP request and response.
+You can run the CLI in verbose mode with the flag `-v`, this will print truncated information about the HTTP request and response. To print all information use the flag `-d` for debug.
```
Comment (bpoole16) [inline docs/rest_api.md]: Made update to docs here.

File: docs/rest_api.md [hunk 19]
```diff
@@ -70,7 +70,9 @@ The OpenWhisk API supports request-response calls from web clients. OpenWhisk re
...
+
+**Note** Only HTTP request and response bodies will be truncated if they exceed 1000 bytes.
```
Comment (bpoole16) [inline docs/rest_api.md]: Made update to docs here.

**Comment by mdeuser** [comment]
@bpoole16 - what will be the output of `wsk action get LARGEACTION` when the exec.code field is quite large?  will the rest of the action output be intact?

**Comment by bpoole16** [comment]
Originally yes, it would just limit the code field and the rest of the resp body would be normal. With James suggestion it cuts off the resp body after 1000 bytes.

**Comment by bpoole16** [comment]
PG 4 632 passed
